services:
  - type: web
    name: giftistry-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your-mongo-uri
      - key: JWT_SECRET
        value: your-secret-key
    staticPublishPath: uploads
